### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [ximitt/exercicio-0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

O principal problema da sua entrega está na falta de otimização no uso do seu código CSS. Note a quantidade de código duplicado entre `tarefa`, `concluida` e `excluida`. 

https://github.com/ximitt/exercicio-0.5.1/blob/e5424a4ce52e56b948dd3f5f5018a43edc86f6f8/style.css#L74-L86

https://github.com/ximitt/exercicio-0.5.1/blob/e5424a4ce52e56b948dd3f5f5018a43edc86f6f8/style.css#L55-L67

https://github.com/ximitt/exercicio-0.5.1/blob/e5424a4ce52e56b948dd3f5f5018a43edc86f6f8/style.css#L94-L106

Você pode evitar essa duplicação de código fazendo com que todos o CSS comum entre as telas fica em um arquivo CSS e as variações em outro.

Você pode evitar isso fazendo uso de duas classes. Adicionando em uma classe as propriedades comuns e tratando as exceções (ou sobreescritas) em outra classe. Veja um exemplo abaixo. 

```css
.menu {
    width: 30em;
    border-radius: 15px;
    border: 2px #8FD14F solid;
    margin: 15px;
    margin-left: 43.3em;
    text-align: center;
    text-decoration: none;
    font-family: ubuntu;
    color: white;
    transition: 0.2s ease-in-out;
}

.pendente {
    background-color: var(--cor-pendentes);
}
```

```html
 <div class="menu pendente"> <p> <b> Trocar de computador </b> </p> 
```

**Nota:** 8.5

### Comentários

https://github.com/ximitt/exercicio-0.5.1/blob/e5424a4ce52e56b948dd3f5f5018a43edc86f6f8/style.css#L1-L4

Existem várias partes do seu código mal indentado. 

Você pode aplicar a indentação automatica do VS Code seguindo os passos:
1) CTRL + p
2) Digite "> format document" (Note o `>`) 

[^1]: [Caminhos: entenda as diferenças entre absolutos e relativos](https://www.alura.com.br/artigos/caminhos-entenda-diferencas-entre-absolutos-relativos?gclid=CjwKCAjw9J2iBhBPEiwAErwpeZOH615fG9QWBpSN2UuIKVbpf6WWD9sknST-4DwVDHzcCBBuMOYuzhoCbNsQAvD_BwE)
[^2]: [CSS Selectors ─ Element Element Selector](https://www.w3schools.com/cssref/sel_element_element.php)
[^3]: [CSS Variables ─ An Introduction](https://youtu.be/PHO6TBq_auI)
[^4]: [HTML Lists](https://www.w3schools.com/html/html_lists.asp)
